/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("io.github.goooler.shadow") version "8.1.5" // Use fork until shadow has updated to Java 21
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://papermc.io/repo/repository/maven-public/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://repo.inventivetalent.org/content/groups/public/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.bstats:bstats-base:3.0.0") { isTransitive = false }
    compileOnly("org.bstats:bstats-bukkit:3.0.0") { isTransitive = false }
    api("org.inventivetalent.spiget-update:bukkit:1.4.6-SNAPSHOT") { isTransitive = false }
    compileOnly("io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7")
    // Databases
    implementation("org.jdbi:jdbi3-core:3.49.1")
    implementation("org.jdbi:jdbi3-sqlobject:3.49.1")
    implementation("org.jdbi:jdbi3-postgres:3.49.1")
    implementation("com.zaxxer:HikariCP:6.2.1")
    implementation("org.postgresql:postgresql:42.7.5")
}

group = "de.erethon"
version = "1.5.7"
description = "Bedrock"
java.sourceCompatibility = JavaVersion.VERSION_21

tasks {
    shadowJar {
        archiveFileName.set("bedrock-${version}.jar")
        dependencies {
            include(dependency("org.bstats:bstats-base:3.0.0"))
            include(dependency("org.bstats:bstats-bukkit:3.0.0"))
            include(dependency("org.inventivetalent.spiget-update:bukkit:1.4.6-SNAPSHOT"))
            include(dependency("org.jdbi:jdbi3-core:3.49.1"))
            include(dependency("org.jdbi:jdbi3-sqlobject:3.49.1"))
            include(dependency("org.jdbi:jdbi3-postgres:3.49.1"))
            include(dependency("com.zaxxer:HikariCP:6.2.1"))
            include(dependency("org.postgresql:postgresql:42.7.5"))
        }
        relocate("org.bstats", "de.erethon.bedrock.bstats")
        relocate("org.inventivetalent.update.spiget", "de.erethon.bedrock.spiget")
        relocate("org.jdbi", "de.erethon.bedrock.jdbi")
        relocate("com.zaxxer.hikari", "de.erethon.bedrock.hikari")
        relocate("org.postgresql", "de.erethon.bedrock.postgresql")
    }
    javadoc {
        options.encoding = Charsets.UTF_8.name()
    }
    val javadocJar by creating(Jar::class) {
        dependsOn(javadoc)
        archiveClassifier.set("javadoc")
        from(javadoc)
    }
    val sourcesJar by creating(Jar::class) {
        archiveClassifier.set("sources")
        from(sourceSets.main.get().allSource)
    }
    processResources {
        filteringCharset = Charsets.UTF_8.name()
    }

    assemble {
        dependsOn(shadowJar)
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
    options.release.set(21)
    options.compilerArgs.add("--enable-preview")
}

publishing {
    repositories {
        maven {
            name = "erethon"
            url = uri("https://reposilite.fyreum.de/snapshots/")
            credentials(PasswordCredentials::class)
            authentication {
                create<BasicAuthentication>("basic")
            }
        }
    }
    publications {
        create<MavenPublication>("maven") {
            groupId = "${project.group}"
            artifactId = "bedrock"
            version = "${project.version}"

            from(components["java"])
        }
    }
}

